name: amazon_returns_ENV
channels:
  - conda-forge
  - defaults # It's good practice to have defaults as a fallback

dependencies:
  # --- CONDA PACKAGES ---
  # Let Conda handle the entire core data science stack first
  # to ensure binary compatibility between numpy, pandas, etc.
  - python=3.12
  - pip
  - numpy # Explicitly install numpy with conda
  - pandas
  - streamlit
  - matplotlib
  - plotly
  - watchdog
  - python-dotenv
  - pydantic
  - httpx
  - distro
  - duckdb
  - sqlglot
  - sqlalchemy
  - astor
  - jiter

  # --- PIP PACKAGES ---
  # Pip will run after Conda is finished and use the
  # libraries Conda has already installed.
  - pip:
    - pandasai
    - streamlit-option-menu
    - openai
